name: Cancellations

on:
  schedule:
    - cron: "0 6 * * *"  # Runs at 6 AM UTC every day
  workflow_dispatch:  # Allows for manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run cancellation scraper
      run: python "scripts/python scrape_parkrun_cancellations.py"

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add cancellations.json
        git commit -m "Update Parkrun cancellations"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
